site_name: Qryptix Documentation
site_description: Quantum-encrypted AI compute for the post-quantum era
site_url: https://qryptix.readthedocs.io
repo_url: https://github.com/qryptix/documentation
repo_name: qryptix/documentation
edit_uri: ""

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
    - toc.follow
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  # Optional: add branding later
  # logo: assets/qryptix-logo.svg
  # favicon: assets/favicon.png

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Features: features.md
  - How It Works: how-it-works.md
  - Use Cases: use-cases.md
  - Technology Stack: technology.md
  - Tokenomics: tokenomics.md
  - Security & Compliance: security.md
  - Developer Resources: developers.md
  - Roadmap: roadmap.md
  - FAQ: faq.md
  - Conclusion: conclusion.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
